# Generated by Django 2.1.2 on 2018-10-30 23:31

from django.db import migrations


def add_default_crusts_and_ingredients(apps, schema_editor):
    """Adds a couple of Crust and Ingredient objects to the database"""

    # Create all of the Crust objects
    crust = apps.get_model('workshop', 'Crust')

    crusts = ['Thin', 'Medium', 'Thick', 'Cheese', 'Chicago Style']

    crust_objects = []
    for item in crusts:
        crust_objects.append(crust(type=item))

    crust.objects.bulk_create(crust_objects)

    # Create all of the Ingredient objects
    ingredient = apps.get_model('workshop', 'Ingredient')

    ingredients = [
        'Anchovies', 'Bacon', 'Gummy Bears', 'Mushrooms', 'Olives', 'Pepperoni'
    ]

    ingredient_objects = []
    for item in ingredients:
        ingredient_objects.append(ingredient(name=item))

    ingredient.objects.bulk_create(ingredient_objects)


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_default_crusts_and_ingredients)
    ]
