# Generated by Django 2.1.2 on 2018-10-31 15:58

from django.db import migrations


def add_default_pizzas(apps, schema_editor):
    """Adds a couple of Pizza objects to the database"""

    # Create all of the Crust objects
    crust = apps.get_model('workshop', 'Crust')
    ingredient = apps.get_model('workshop', 'Ingredient')
    pizza = apps.get_model('workshop', 'Pizza')

    pizza_objects = list()

    pizza_objects.append(pizza(
        city='Chicago',
        state='IL',
        likes=5,
        dislikes=1,
        crust=crust.objects.get(pk=5),
        name='Chicago-Style',
        summary=(
            'A very thick crusted deep-dish pizza, that is almost like a pie.'
        )
    ))

    pizza_objects.append(pizza(
        city='San Diego',
        state='CA',
        likes=27,
        dislikes=0,
        crust=crust.objects.get(pk=1),
        name='Anchovies Pizza',
        summary=(
            'A nice anchovies pizza where the strong briny, salty flavors of'
            ' olives and anchovies complement each other nicely.'
        )
    ))

    pizza_objects.append(pizza(
        city='New York',
        state='NY',
        likes=2,
        dislikes=3,
        crust=crust.objects.get(pk=4),
        name='Supreme',
        summary=(
            'Contains everything you could ever want!'
        )
    ))

    pizza.objects.bulk_create(pizza_objects)

    # Chicago-style
    pizza.objects.get(pk=1).ingredients.add(
        ingredient.objects.get(pk=2),
        ingredient.objects.get(pk=4),
        ingredient.objects.get(pk=5),
        ingredient.objects.get(pk=6),
    )

    # Anchovies pizza
    pizza.objects.get(pk=2).ingredients.add(
        ingredient.objects.get(pk=1),
        ingredient.objects.get(pk=4),
        ingredient.objects.get(pk=5),
    )

    # Supreme
    pizza.objects.get(pk=3).ingredients.add(
        ingredient.objects.get(pk=1),
        ingredient.objects.get(pk=2),
        ingredient.objects.get(pk=3),
        ingredient.objects.get(pk=4),
        ingredient.objects.get(pk=5),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_create_crusts_and_ingredients'),
    ]

    operations = [
        migrations.RunPython(add_default_pizzas)
    ]
