# Generated by Django 2.1.2 on 2018-10-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0003_create_pizzas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
